# Generated by Django 4.0.2 on 2022-02-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_alldestinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='promo',
            field=models.BooleanField(default=False),
        )
    ]
